# Generated by Django 6.0 on 2025-12-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
