# Generated by Django 6.0 on 2025-12-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loan_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='notified',
        ),
    ]
